### ISSUE TITLE
ファイル未Open かつ　ファイル新規作成していない場合編集を許すか

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#102]
現状ファイル未Open かつ　ファイル新規作成していない場合も編集ができるが、これは望ましい挙動なのか

許す場合はステータスバーを`filename...`ではなく新規作成ボタンを押した後と同じ挙動にするべきなので

**Comment by YSRKEN** [comment]
メニューの「新規作成」を「リセット」と名前変更すれば解決？

**Comment by yumetodo** [comment]
ですかね。
では許す方向でfixします

**Comment by yumetodo** [comment]
@YSRKEN これでいいですかね？リセットボタンの内部名は変えてないですが

**Comment by YSRKEN** [comment]
はい、大丈夫です。
