### ISSUE TITLE
マップエディタを使用後にシュミレーションを実行しようとすると実行されない

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#108]
再現手順：
マップエディタでおもむろにファイルを開く→
シミュレーション画面で自艦隊と敵艦隊を指定→
ボタンを押してもシミュレーションが実行されない

ただしcommit 4bd6cb999192bf8cea97b9af20de3e841c3427f6 の時点でこのバグは出てこなかった。
commit e4050c9f29b61cc558a554ab982459528d85a261 や
commit 62d5ac0b0b3d361900595af5dffdb59391a7f973 の時点ではどうだったかは未調査。

**Comment by yumetodo** [comment]
b17b3ef1f8b5ff6da2eb6273b5bb350745066da6
時点では多分動いてる
