### ISSUE TITLE
GUIでの艦隊エディタにおける艦娘状態変更反映についての不具合

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#109]
GUIにて、艦隊エディタにおける艦娘選択欄で選択した艦娘について、レベル・運・cond値が「数値を書き換えただけ」で即座に反映されてしまう。
本来なら、選択→数値書き換え→変更ボタンで初めて変更されないとならない。
(この不具合により、GUIで艦娘を追加する際、艦娘Aを追加→情報を艦娘Bに書き換え追加→艦娘Aのレベルが艦娘Bのレベルと一致してしまう)

**Comment by yumetodo** [comment]
どういうことでしょう。私が想定する操作は
1. 艦種選択
2. 艦名選択
3. レベル・運・cond値入力
4. 追加

を繰り返すというものです。この場合

> 艦娘Aのレベルが艦娘Bのレベルと一致

~~ということは起きません。個人的には~~

> 選択→数値書き換え→変更ボタンで初めて変更されないとならない。

というのは使いにくくて仕方ないので、テキストボックスのイベントを追加したんですが

---

追記

ああ、そういうことか、直します。艦名が変わってたら変更しないようにします

**Comment by YSRKEN** [comment]
> ということは起きません。

と思いきや、左欄(KammusuSelectListBox)をクリックしてしまうと、上記のような謎書き換えが発生してしまいました。艦隊を2回切り替えれば、KammusuSelectListBox.SelectedIndex=-1となって謎書き換えを回避できますが……

**Comment by yumetodo** [comment]
@YSRKEN まだ実行してないけど多分これでいいはず・・・

**Comment by yumetodo** [comment]
ダメだな・・・

**Comment by yumetodo** [comment]
いろいろ動かしてみた結果、これでいいはず
@YSRKEN

**Comment by YSRKEN** [comment]
直っているようです。ありがとうございました。
