### ISSUE TITLE
WG集積地特効などを追加

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#119]
なお、集積地棲姫やPTの正確なパラメータが一部わからない模様

**Comment by YSRKEN** [comment]
6-4を擬似的にでも再現するため、集積地棲姫や砲台など一部のデータを無理やり再現することにする。
ただし付け足した旨とその箇所を明記する。

**Comment by YSRKEN** [comment]
https://github.com/YSRKEN/KanColleSimulator_KAI/issues/132
これが片付いたので、やっとこのissuesに取り組める

**Comment by YSRKEN** [comment]
修正箇所は、Simulator::CalcDamage関数ぐらいかと。読んだら、「陸上型」(カテゴリ)に対して「三式弾のキャップ前乗算」「WG42のキャップ前加算」「WG42のニートへのキャップ後乗算」「PT子鬼群補正」しか行っていなかったことが判明。えーっと、砲台とゴスロリへのキャップ前補正と、ニートへの大発系キャップ後補正も追加しなくては
http://ja.kancolle.wikia.com/wiki/%E7%89%B9%E5%8A%B9

**Comment by YSRKEN** [comment]
@yumetodo せんせー！
Kammusu::AnyOf関数についてですが、対象の指定として
「SID("何とか")」とすれば「対象の艦1隻(同名の艦が複数存在すればエラー)」、
「L"艦名"s」とすれば「同名の艦全て」になるのでしょうか？

**Comment by yumetodo** [comment]
@YSRKEN あってます。

`SID`を`Kammusu::AnyOf`に指定したときに呼ばれるoverload

``` cpp
bool Kammusu::AnyOf(const ShipId test) const noexcept;
```

は艦名(正確にはそれを艦船ID(`enum class ShipId`のこと。例えば睦月は`ShipId::ID1`))の一致検索をするもの。集積地棲姫のように一対一対応しない場合は**例外が飛びます**

```
1>  source/lookup.hpp(67,74) :  note: subexpression not valid in a constant expression
1>                  : Contains(pairs, key, detail::IndexOfBlock(pairs, key, offset) + 1) ? throw std::invalid_argument("duplicated key.")
```

文字列を渡したときに呼ばれるoverload

``` cpp
bool AnyOf(const String& test) const noexcept;
```

は**CSV上で艦船IDと艦名が一対一対応する範囲では**、(実行速度を除けば)**上の関数と同じ結果になる**が、集積地棲姫のように一対一対応しない場合は艦名で検索した結果になります。

---

しかしこれ、重複キーをエラーで弾くのはあかんなぁ・・・。文字列比較が入ってしまう・・・。
艦名をコンパイル時にハッシュ化してしまうか・・・？

**Comment by yumetodo** [comment]
なんでハッシュ化したいかというと、艦船IDでの比較はCSV上で艦船IDと艦名が一対一対応しない場合にどうしようもない(型システム的に戻り値の型を動的にできないため)からです。

``` cpp
enum class ShipId {
#define SHIP(PREFIX, ID, NAME, SHIPCLASS, MAX_HP, DEFENSE, ATTACK, TORPEDO, ANTI_AIR, LUCK, SPEED, RANGE, SLOTS, MAX_AIRS, EVADE, ANTI_SUB, SEARCH, FIRST_WEAPONS, KAMMUSU_FLG, POSTFIX)    \
    I ## D ## ID = ID,
#include "ships.csv"
#undef SHIP
};
```

と

``` cpp
    Kammusu(
        const int id, const wstring& name, const ShipClass shipclass, const int max_hp, const int defense,
        const int attack, const int torpedo, const int anti_air, const int luck, const Speed speed,
        const Range range, const size_t slots, const vector<int>& max_airs, const int evade, const int anti_sub,
        const int search, const vector<int>& first_weapons, const bool kammusu_flg, const int level
    );
```

これに手を加えてハッシュ値を`kammusu`クラスに持つようにすれば文字列比較せずに文字列比較とおなじ結果が得られます。ハッシュアルゴリズムは別にMD5でいいと思う。

ただハッシュアルゴリズムをコンパイル時に動かすアルゴリズムの実装とか絶対に自分で書きたくないのでsprout使わせてください。

https://github.com/bolero-MURAKAMI/Sprout/blob/f08464943fbe2ac2030060e6ff20e4bb9782cd8e/sprout/uuid/md5_name_generator.hpp#L92

その場合

``` cpp
if (target_kammusu.AnyOf(SIDH("集積地棲姫")) | target_kammusu.AnyOf(SIDH("集積地棲姫-壊"))) { 
```

みたいに書けるはずです。

速度的には

艦船ID < ハッシュ << (越えられない壁) << std::basic_string::operator==

です。

#64

**Comment by yumetodo** [comment]
SIDについて書きましたが、WIDについても同じことがいえます。

**Comment by yumetodo** [comment]
@YSRKEN @sayurin 問題は実装する価値があるかどうかですね、依存関係増やしてまで。

**Comment by YSRKEN** [comment]
対地特効実装前のメモ

<pre>
入力ファイル名：sample\6-4 秋津洲編成.json, sample\6-4 ACN Light.map
陣形指定：
　単縦陣
　単縦陣
試行回数：100000
スレッド数：4
出力ファイル名：
　output.json
陣形：単縦陣　司令部レベル：120　形式：通常艦隊
　第1艦隊：
　　Верный(Lv94) 37/37
　　大和改(Lv99) 96/96
　　霞改二(Lv94) 31/31
　　大淀改(Lv99) 47/47
　　筑摩改二(Lv99) 58/58
　　秋津洲改(Lv74) 36/36
マス数：3
　Aマス：1艦隊　昼戦のみ
　　軽巡ホ級flagship,雷巡チ級flagship,雷巡チ級flagship,駆逐ハ級後期型,駆逐ロ級後期型,駆逐ロ級後期型　単縦陣
　Cマス：2艦隊　昼戦のみ
　　戦艦ル級flagship,戦艦ル級flagship,軽巡ヘ級flagship,駆逐ニ級後期型,駆逐ニ級後期型,軽母ヌ級elite　単縦陣
　　戦艦ル級flagship,戦艦ル級flagship,軽巡ヘ級flagship,駆逐ハ級後期型,駆逐ハ級後期型,軽母ヌ級elite　単縦陣
　Nマス：2艦隊　昼戦＋夜戦
　　離島棲姫,砲台小鬼,集積地棲姫-壊　単縦陣
　　離島棲姫,砲台小鬼,砲台小鬼　単縦陣
preprocess:25,196,333[ns]
処理時間：2,471[ms]
Aマス到達率：100％
道中撤退率：4.288％
Cマス到達率：95.712％
道中撤退率：68.2307％
Nマス到達率：30.407％
ボスマスにおける統計：
自艦隊：
　第1艦隊：
　　Верный(Lv94)
　　　残耐久：[1～26.0529～37] σ＝12.0333
　　　与ダメージ：[-2,143,179,138～1.83224e+08～2,144,844,731] σ＝4.35881e+08
　　　MVP率：12.6287％ 大破率：12.4445％
　　大和改(Lv99)
　　　残耐久：[1～61.0012～96] σ＝25.3452
　　　与ダメージ：[-2,146,491,789～1.73844e+08～2,146,018,868] σ＝4.10038e+08
　　　MVP率：43.7005％ 大破率：12.1255％
　　霞改二(Lv94)
　　　残耐久：[1～15.1644～31] σ＝10.2372
　　　与ダメージ：[-2,146,374,155～1.75168e+08～2,143,887,646] σ＝4.18248e+08
　　　MVP率：11.106％ 大破率：27.8423％
　　大淀改(Lv99)
　　　残耐久：[1～24.3476～47] σ＝15.501
　　　与ダメージ：[-2,145,308,571～1.76308e+08～2,147,028,463] σ＝4.20231e+08
　　　MVP率：10.3726％ 大破率：25.7408％
　　筑摩改二(Lv99)
　　　残耐久：[1～32.5584～58] σ＝18.7414
　　　与ダメージ：[-2,144,565,459～1.80938e+08～2,146,227,790] σ＝4.32969e+08
　　　MVP率：13.5199％ 大破率：22.0278％
　　秋津洲改(Lv74)
　　　残耐久：[1～16.0802～36] σ＝11.5432
　　　与ダメージ：[-2,146,314,247～1.67252e+08～2,143,948,414] σ＝4.01786e+08
　　　MVP率：8.67235％ 大破率：35.3405％
敵艦隊：
　第1艦隊：
　　離島棲姫(Lv1)
　　　残耐久：[0～248.053～480] σ＝105.255
　　　与ダメージ：[0～151.251～611] σ＝107.535
　　砲台小鬼(Lv1)
　　　残耐久：[0～21.0545～130] σ＝28.0801
　　　与ダメージ：[0～45.8755～453] σ＝54.0673
　　集積地棲姫-壊(Lv1)
　　　残耐久：[0～5.75729～97] σ＝14.9826
　　　与ダメージ：[0～21.7624～204] σ＝25.424
旗艦撃破率：0.38478％
勝率：60.907％
　完全勝利SS：0.0723518％
　勝利S：0.309139％
　勝利A：41.793％
　戦術的勝利B：18.7325％
　戦術的敗北C：24.5832％
　敗北D：14.5098％
　敗北E：0％
</pre>

**Comment by YSRKEN** [comment]
実装後

<pre>
入力ファイル名：sample\6-4 秋津洲編成.json, sample\6-4 ACN Light.map
陣形指定：
　単縦陣
　単縦陣
試行回数：100000
スレッド数：4
出力ファイル名：
　output.json
陣形：単縦陣　司令部レベル：120　形式：通常艦隊
　第1艦隊：
　　Верный(Lv94) 37/37
　　大和改(Lv99) 96/96
　　霞改二(Lv94) 31/31
　　大淀改(Lv99) 47/47
　　筑摩改二(Lv99) 58/58
　　秋津洲改(Lv74) 36/36
マス数：3
　Aマス：1艦隊　昼戦のみ
　　軽巡ホ級flagship,雷巡チ級flagship,雷巡チ級flagship,駆逐ハ級後期型,駆逐ロ級後期型,駆逐ロ級後期型　単縦陣
　Cマス：2艦隊　昼戦のみ
　　戦艦ル級flagship,戦艦ル級flagship,軽巡ヘ級flagship,駆逐ニ級後期型,駆逐ニ級後期型,軽母ヌ級elite　単縦陣
　　戦艦ル級flagship,戦艦ル級flagship,軽巡ヘ級flagship,駆逐ハ級後期型,駆逐ハ級後期型,軽母ヌ級elite　単縦陣
　Nマス：2艦隊　昼戦＋夜戦
　　離島棲姫,砲台小鬼,集積地棲姫-壊　単縦陣
　　離島棲姫,砲台小鬼,砲台小鬼　単縦陣
preprocess:4,946,185[ns]
処理時間：3,120[ms]
Aマス到達率：100％
道中撤退率：4.292％
Cマス到達率：95.708％
道中撤退率：68.5387％
Nマス到達率：30.111％
ボスマスにおける統計：
自艦隊：
　第1艦隊：
　　Верный(Lv94)
　　　残耐久：[1～27.4382～37] σ＝11.4597
　　　与ダメージ：[-2,146,523,454～2.18444e+08～2,147,061,068] σ＝4.89983e+08
　　　MVP率：36.0699％ 大破率：9.0731％
　　大和改(Lv99)
　　　残耐久：[1～63.5408～96] σ＝25.031
　　　与ダメージ：[-2,143,285,470～2.02442e+08～2,139,559,921] σ＝4.42055e+08
　　　MVP率：19.3384％ 大破率：10.3716％
　　霞改二(Lv94)
　　　残耐久：[1～16.8816～31] σ＝10.3166
　　　与ダメージ：[-2,147,228,064～2.12109e+08～2,144,106,797] σ＝4.70944e+08
　　　MVP率：13.6727％ 大破率：20.7831％
　　大淀改(Lv99)
　　　残耐久：[1～26.55～47] σ＝15.4518
　　　与ダメージ：[-2,144,995,651～2.13578e+08～2,147,331,566] σ＝4.72903e+08
　　　MVP率：13.8222％ 大破率：20.3647％
　　筑摩改二(Lv99)
　　　残耐久：[1～34.8338～58] σ＝18.6017
　　　与ダメージ：[-2,145,860,630～2.15048e+08～2,143,066,387] σ＝4.83971e+08
　　　MVP率：9.5148％ 大破率：18.2525％
　　秋津洲改(Lv74)
　　　残耐久：[1～17.9901～36] σ＝11.712
　　　与ダメージ：[-2,145,315,000～2.00416e+08～2,146,112,865] σ＝4.50118e+08
　　　MVP率：7.58195％ 大破率：27.9366％
敵艦隊：
　第1艦隊：
　　離島棲姫(Lv1)
　　　残耐久：[0～132.636～480] σ＝146.691
　　　与ダメージ：[0～135.104～626] σ＝109.788
　　砲台小鬼(Lv1)
　　　残耐久：[0～2.36963～130] σ＝11.265
　　　与ダメージ：[0～27.4472～380] σ＝41.6908
　　集積地棲姫-壊(Lv1)
　　　残耐久：[0～0.0786424～78] σ＝1.82504
　　　与ダメージ：[0～16.857～181] σ＝21.0298
旗艦撃破率：46.6341％
勝率：94.5668％
　完全勝利SS：3.58673％
　勝利S：42.8348％
　勝利A：47.2552％
　戦術的勝利B：0.89004％
　戦術的敗北C：3.49042％
　敗北D：1.94281％
　敗北E：0％
</pre>

**Comment by yumetodo** [comment]
処理時間：2,471[ms]
から
処理時間：3,120[ms]
か・・・やっぱり文字列比較重そう・・・？
