### ISSUE TITLE
TODOリスト

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#12]
※順序は時系列順ですが前後することもありえます
- [ ] 結局、改修度と熟練度は別々に持つ必要が出てきたらしいですがどうしよう？
- [ ] ご注文は卯月ですか？
- [x] GUIにて、艦娘選択欄で選択した艦娘について、レベル・運・cond値が「数値を書き換えただけ」で即座に反映されてしまう。本来なら、選択→数値書き換え→変更ボタンで初めて変更されないとならない
  (この不具合により、GUIで艦娘を追加する際、艦娘Aを追加→情報を艦娘Bに書き換え追加→艦娘Aのレベルが艦娘Bのレベルと一致してしまう)
- [x] なぜか大潮改と木曽改二にて、GUI上で装備を追加できなかったので要修正
  (テキストエディタ等で適当に装備を追加すると、以降は編集できるようになった)
- [x] 1-1.mapを読み込んでくれない不具合

**Comment by yumetodo** [comment]
- [x]  csv読み込みのutf-8対応
- [ ] ~~`-fcsv-charset`~~, `-foutput-charset`, `-fstdout-charset`の実装

**Comment by yumetodo** [comment]
csv読み込みを、Shift-JIS, UTF-8両対応させるには、VSかgccでしかコンパイルできないか、自力で文字列リテラルをエンコードするしかなさそう・・・、辛い。

**Comment by YSRKEN** [comment]
CSVはどうせこちらで用意しますので、片方固定で良いと重いますが……

**Comment by yumetodo** [comment]
じゃあShift-JIS切り捨てで
