### ISSUE TITLE
乱数生成関数を他のクラスに使用させたい

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#13]
並列演算が売りですので、Simulatorクラスのメンバ関数にあるRandInt()やRandReal()を他の関数に使用したいのですが、Cで言うところの関数ポインタのC++版って確か関数オブジェクトでしたよね？
今回のケースの場合、どのように引数を設定すれば良いと思いますか？

**Comment by yumetodo** [comment]
まず注意することは、スレッド間では共有できないことですね、`std::mt19937`とかの乱数系クラスは。

> 並列演算が売りですので、Simulatorクラスのメンバ関数にあるRandInt()やRandReal()を他の関数に使用したいのですが

もう少し具体的にお願いします

単に関数オブジェクトというと`operator()`があるクラスのことですが

**Comment by YSRKEN** [comment]
もちろん存じておりますわ。このことから、Simulatorクラス毎に「std::mt19937 mt;」と記述し、コンストラクタで初期化するようにしたのです。同じSimulatorクラスのメンバ関数の中でRandInt()などを使うのは簡単ですが、そうでなくFleetクラスやKammusuクラスなどでRandInt()を使いたい場合が……こうなったら、Simulatorクラスのthisポインタを渡してやるのが一番簡単ですかね？

**Comment by yumetodo** [comment]
その前に少し質問させてください。

``` cpp
    Simulator(const vector<Fleet> &fleet, const unsigned int &seed) {
        fleet_ = fleet;
        mt = std::mt19937(seed);
        rand = std::uniform_real_distribution<double>(0.0, 1.0);
    }
```

コンストラクタがseedを要求するのは理由があるのでしょか？seedを固定する理由がよくわかりません

**Comment by yumetodo** [comment]
乱数生成器の共有で手っ取り早く、かつ安全なのは、main関数で

``` cpp
auto mt = std::make_shared<std::mt19937>(/* some seed*/);
```

とかして、各クラスのコンストラクタ経由で渡してしまうことだと思います。

**Comment by YSRKEN** [comment]
それはですね、main関数を見ていただけたら分かるかと思いますが、各スレッド(各試行)ごとに別々のシードであることを保証したいからですわ。

**Comment by yumetodo** [comment]
ああ、そういうことか。

ちょっと考えます。

**Comment by YSRKEN** [comment]
乱数の件についてはとりあえずthisポインタを渡す戦法でやってみます。

**Comment by yumetodo** [comment]
いや、それダメです

**Comment by yumetodo** [comment]
@YSRKEN 
とりあえず
FleetクラスとKammusuクラスに乱数を渡せるようにします。しばしお待ちを

**Comment by YSRKEN** [comment]
ポインタですがconst修飾させてますがダメでしょうか？
(ちなみに単に乱数の結果(intやdouble)を引数に渡すのではダメです。関数ポインタかそれに類似したものが求められます)

**Comment by yumetodo** [comment]
乱数生成器ごと各クラスに渡せばいいですよね？

**Comment by YSRKEN** [comment]
はい。

**Comment by YSRKEN** [comment]
(正確には、RandIntかRandRealかが渡せれば良い)

**Comment by yumetodo** [comment]
乱数用のクラスを作ります。shaed_ptrで乱数生成器を持っているものを考えてくだい。
どのみちあのRandIntの実装はダメなので書き直しですし。

**Comment by YSRKEN** [comment]
え、アレではダメなのですか？

**Comment by yumetodo** [comment]
@YSRKEN 乱数生成クラスはできました。FleetクラスとKammusuクラスに乱数を渡せるようにします。

**Comment by yumetodo** [comment]
#15 で解決したはずなのでcloseします。何かあればreopenしてください
