### ISSUE TITLE
Git Flow導入

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#140]
> https://twitter.com/YSRKEN/status/786930802063908868
> 
> <blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">【重要なお知らせ】<br>KCS_KAIにもGit Flowを導入します。<br>現在はVer.2.1.1ですので、Ver.2.1.2ができるまでmasterリポジトリにマージされない格好になります。</p>&mdash; YSR@MIPマスター (@YSRKEN) <a href="https://twitter.com/YSRKEN/status/786930802063908868">2016年10月14日</a></blockquote>
> 
# 影響範囲

現状出ている
#104 : Use data bind
#129 : method-chain-like function : support enum type

は投げ直し、
#137 : Clang with Microsoft CodeGen更新(7月)に伴うBreaking Changeへの対応

は保留する必要あり

**Comment by yumetodo** [comment]
問題として、まずすでに #107 のmergeなどにより 20commitすすんでおり、中途半端なこと、#104 はconflictしていることが挙げられます

**Comment by YSRKEN** [comment]
- 「中途半端なこと」にはどういった問題がありますか？
- プルリクを受け入れても問題ないのならmergeします
- sayurinさんが戻ってくるのを待つべきか、二人でできる場所を進めていくか……

**Comment by yumetodo** [comment]
- 中途半端なのでGit Flowのメリットがないことでしょうか。あれはmasterがきれいにするのが目的なので、中途半端な時点でそれは達成できず、手間だけ増えます
- #104 のconflictは大きくはなさそうなのでまあ直せなくはないと思います。

**Comment by YSRKEN** [comment]
- Git Flowは導入したてなので半端な部分が出てくるのは仕方ないです……ごめんなさい
- とりあえず、できるところ(CUI修正など)を進めていきます

**Comment by yumetodo** [comment]
うーん、#104 のconflictは間違いなく #109 が原因の半分以上だわ。

**Comment by yumetodo** [comment]
![image](https://cloud.githubusercontent.com/assets/10869046/19412094/1ea1911c-9349-11e6-876d-4ab069c837ad.png)
どうやら`develop` branchが始動したようだ。

**Comment by YSRKEN** [comment]
これもう閉じていいかしら？

**Comment by yumetodo** [comment]
閉じ**ました**
