### ISSUE TITLE
GUIの艦隊エディタにおける自動スクロールがおかしいので修正

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#159]
![default](https://cloud.githubusercontent.com/assets/3734392/19646002/807d1b50-9a32-11e6-9cb6-7444c8b26e77.png)
装備については自動スクロールできたものの……
おそらく、ships.csvを一新したので「魚雷艇」が艦種としてちゃんと出せるようになったからだと思われる

**Comment by YSRKEN** [comment]
マップエディタはセーフかと思いきや、タ級flagshipが巡洋戦艦扱いになってたのでｱｯｱｯとなってます

**Comment by yumetodo** [comment]
今回はそこまでしないにしても、これは艦名抽出の部分を切り出して自動テストできるようにするべきだな・・・。
ref #152

**Comment by yumetodo** [comment]
艦隊エディタの方は原因特定しました

**Comment by yumetodo** [comment]
@YSRKEN 戦艦タ級flagshipはどうなるのが正しいのですか？

というかcsv側の問題な気がする。

**Comment by YSRKEN** [comment]
……ああ、戦艦タ級flagshipは高速戦艦ですね。上記のは忘れてください

**Comment by YSRKEN** [comment]
スクロールが直ったのでclose
