### ISSUE TITLE
Releaseページの説明文は短くあるべきではないか

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#164]
https://github.com/YSRKEN/KanColleSimulator_KAI/releases

現状README.mdまるまるコピペしているが、ほとんどいらないゴミ情報だと思う。必要なのは変更点ではないのか。

今後のReleaseページの説明文は最新の変更点(必要であればIssue番号記載)のみ記すことを提案する

**Comment by YSRKEN** [comment]
Ver.2.2.0リリース時に検討します
