### ISSUE TITLE
Clang with Microsoft CodeGen対応(Visual Studio 2015 Update1)

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#2]
https://github.com/YSRKEN/KanColleSimulator_KAI/commit/445582e3450ceb00a05f0f24f6212af8239f8027
ではClang with Microsoft CodeGen向けの構成を削除しているが、開発時のコンパイルエラーを見るために有用なので、構成はあったほうがいいのではないか？

というわけで
https://github.com/YSRKEN/KanColleSimulator_KAI/commit/445582e3450ceb00a05f0f24f6212af8239f8027
の一部revertを提案する

**Comment by YSRKEN** [comment]
分かりました。えっと、一部ファイルだけ差し戻すということでしょうか？

**Comment by yumetodo** [comment]
ですね、今Mergeしてるのでその過程で戻しておきます
