### ISSUE TITLE
SetRandGenerator関数はどの場合に呼ぶべき？

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#25]
ご教示いただけるとありがたいです。

**Comment by yumetodo** [comment]
各クラスで乱数生成器を共有する必要があります。
したがって、Simulatorクラスで作った乱数生成器を各クラスに渡すために現在使っています。

乱数生成器が必要なクラスができた場合は
1. `SharedRand`型の変数をメンバーに追加
2. ctorまたは何らかのメンバー関数を通じて1で追加した変数にコピーできるようにする(コピーすることで乱数生成器が共有されます、moveじゃないです)
3. 2は必要になったクラスで最初に乱数を生成するまでに実施する、じゃないと`KCS_except::missing_rand_generator`例外が飛ぶ

**Comment by YSRKEN** [comment]
ありがとうございました。
