### ISSUE TITLE
make_unique_rand_arrayがマルチスレッド時にコケる？

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#26]
main.cppの27行目に

> auto seed = make_SharedRand().make_unique_rand_array<unsigned int>(config.GetThreads());

とありますが、ここでconfig.GetThreads()が2以上だとコケるようです。

> It was stopped by unhandled exception.
> excetopn : invalid_argument

**Comment by yumetodo** [comment]
あや？
調べます

**Comment by yumetodo** [comment]
多分修正できたと思います。
