### ISSUE TITLE
KammusuIndexは何か

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#27]
KammusuIndexは現在`std::vector<std::size_t>`にdefineされているが、どうも2要素しか使っていないのではないか？
2要素だけではないならば反例を教えて下さい。
2要素だけなら、構造体にするか、std::pairにするのを提案します
@YSRKEN

**Comment by YSRKEN** [comment]
2要素しかありませんわ(艦隊番号と、艦隊における位置番号)。構造体でもstd::pairでもどちらでも構いませんが、簡素さから考えると後者で良いと思われますわ。

**Comment by yumetodo** [comment]
@YSRKEN 
構造体のほうがいいと思うんですが。std::pairだと汎用的すぎてそれぞれ何を意味するかわかりにくいので

**Comment by YSRKEN** [comment]
でしたらお任せします。速度的にはtupleより速くなるのでしょうか？

**Comment by yumetodo** [comment]
tupleもpairも自作構造体も速度に差は出ませんが・・・？

**Comment by yumetodo** [comment]
``` cpp
struct KammusuIndex {
    std::size_t fleet_no;
    std::size_t fleet_i;
};
```

こんな感じの構造体かな

艦隊における位置番号ってもう少し言うと何でしょう

**Comment by yumetodo** [comment]
変更しました
