### ISSUE TITLE
ResultStat::all_count_の型について

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#32]
https://github.com/sayurin/KanColleSimulator_KAI/blob/master/KCS_CUI/source/other.hpp#L36
`ResultStat::all_count_`の型はintではなくsize_tにするべきではないか

これは

```
other.cpp(233): warning C4267: '=': 'size_t' から 'int' に変換しました。データが失われているかもしれません。
```

の警告対策です

**Comment by YSRKEN** [comment]
修正しましたわ
