### ISSUE TITLE
for文内での変数宣言にautoを使うべきでは無いのではないか

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#33]
``` cpp
for (auto bi = 0; bi < kBattleSize; ++bi)
```

こういう奴。`bi`の型がわかりにくい。**実際、signed<->unsigend回りで何回かミスをしている。**

型を明示的に書くか、

あるいは
http://secret-garden.hatenablog.com/entry/2015/02/28/001934
のような( [@pink_bangbi](https://twitter.com/pink_bangbi) 氏作)固定回ループ用のヘルパークラスを使って、**range-based forを使う**ようにするか

を提案する

**Comment by YSRKEN** [comment]
確かに……型推論のために0uと書きまくるのもバカバカしいので修正しておきます。

**Comment by yumetodo** [comment]
@YSRKEN えっとどういう方向に？

**Comment by YSRKEN** [comment]
既にpushしました。

**Comment by yumetodo** [comment]
確認しました。結構な数for文ありますね・・・。

**Comment by yumetodo** [comment]
こういう時はIssue番号をcommitメッセージに加えていただけると有りがたかったです

**Comment by YSRKEN** [comment]
分かりました。今度からはそういたします。
