### ISSUE TITLE
並列処理関係について

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#34]
OpenMPを有効にしてビルドすると、スレッド数指定を1にした(「-t 1」にした)場合でもフルロードされてしまう問題を見つけました。
num_threads指定でのカッコ内の数値は別に定数でなくてもいいですしし、そもそも「config.GetThreads()」の値はきちんと1になっているのに……。

**Comment by yumetodo** [comment]
> フルロードされてしまう

？

**Comment by YSRKEN** [comment]
なぜか全コア使われてしまうということです。

**Comment by yumetodo** [comment]
もしかして：自動並列化

アセンブリにそれっぽい並列系関数の呼び出しがあるかな・・・？

**Comment by YSRKEN** [comment]
@yumetodo 並列処理関係ついでですが、マップモードについても並列処理させたいのですけれど、どのように改修すべきでしょうか？

**Comment by YSRKEN** [comment]
解決しましたので閉じます
