### ISSUE TITLE
WeaponとKammusuのデフォルトCtorを移譲コンストラクタに

### ISSUE THREAD

**Issue by loliGothicK** [YSRKEN/KanColleSimulator_KAI#4]
デフォルトコンストラクタが初期化子で初期化しているが
デフォルトコンストラクタを移譲コンストラクタにする

**Comment by yumetodo** [comment]
@LoliGothick 
この場合delegateできるんですかね？

**Comment by loliGothicK** [comment]
コンストラクタのデリゲートはできます

**Comment by YSRKEN** [comment]
移譲コンストラクタでググりましたが、冗長さが消えて良いですねこれ……！

**Comment by yumetodo** [comment]
@LoliGothick pull requestお願いしていいですか？
#5 がマージされた後のほうが楽だと思いますが。

**Comment by YSRKEN** [comment]
@yumetodo とりあえずweaponとkammusuを移譲コンストラクタにしました。#5はこれから処理します。

**Comment by yumetodo** [comment]
@YSRKEN 先に作業するとMergeしなきゃいけないから後に、と言いたかったが時遅しだった

**Comment by yumetodo** [comment]
なんか #6 が空気になっちゃったな・・・
#6 をreject、これはcloseでいいと思うんですがどうでしょうか？ @YSRKEN @LoliGothick
