### ISSUE TITLE
version表示機能の追加

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#42]
version.hにマクロで適当に定義してそれを表示できるようにする

**Comment by YSRKEN** [comment]
いいですね！例えば「-v」とでも入力すれば出せる感じにしますか？

**Comment by yumetodo** [comment]
すでに仮組みしてあるので
1. version.hにマクロで適当に定義
2. config.cppのdetail::print_verisonを編集

するだけです

**Comment by YSRKEN** [comment]
現状、version.hはまだ追加されていませんが、リリース前にサクッと追加しますか？

**Comment by yumetodo** [comment]
しましょう

**Comment by yumetodo** [comment]
C#とversion.h共有できたらいいんだけどなぁ。ざっと調べた感じdllにしろとか言うわけわかめな結果になった
