### ISSUE TITLE
MapData#GetFleet関数でちゃんと乱数を使いたい

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/KanColleSimulator_KAI#49]
現状は`return fleet_[p][0];`と書いてますが、本来なら
`return fleet_[p][rand_.RandInt(fleet_[p].size())];`と書きたいのです。しかしそうすると、
`オーバーロードされた関数 "SharedRand::RandInt" のインスタンスが引数リストおよびオブジェクトと一致しません (オブジェクトに一致を妨げる型修飾子があります)`
と表示されてしまいます。何がいけないのでしょうか？

**Comment by yumetodo** [comment]
commitメッセージのとおりです
