### ISSUE TITLE
SharedRandは各クラスにおいてmutableであるべきか

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#51]
まずmutableとは
http://ezoeryou.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml#dcl.stc.mutable
http://www.slideshare.net/barfoo102/const-26663804 (10ページ)
クラスのメンバーにつけるStorage class specifiersのことである。
# 提案

現在各クラスに

``` cpp
class foo {
    SharedRand rand_;
    //以下略
    void bar(){ //const 指定できない
        int r = rand_(0, 5);
        //do something
    }
};
```

のように乱数生成器を置いているが、この乱数生成器の実体はSharedRandクラス内部のstd::shared_ptrによって確保されたメモリー空間上にあり、各クラスで共有している。

ならばmutableにしたほうがいいのではないか
## メリット
- 乱数生成器をconstメンバー関数からも使える
- 見かけ上constメンバ関数にできそうなゲッターをconst指定できる( #49 からそういう欲求があるのは自明 )
## デメリット
- mutableは乱用してはいけない

**Comment by bolero-MURAKAMI** [comment]
横からすみません。
SharedRandクラスが生成器のポインタを保持する前提であれば、SharedRandクラスの各メンバ関数はconst修飾できます。
SharedRandクラスの側の実装を弄れば、包有するクラス側でmutable指定せずとも、SharedRandクラスのメンバ関数を呼び出すことができます。

**Comment by yumetodo** [comment]
@bolero-MURAKAMI
あれ、できましたっけ・・・。
現状
https://github.com/YSRKEN/KanColleSimulator_KAI/blob/master/KCS_CUI/source/random.hpp#L37
こういう風に持っているんですが・・・。

**Comment by bolero-MURAKAMI** [comment]
shared_ptr&lt;T&gt; const から T の非constメンバを呼び出すことができるので可能です。
例： http://melpon.org/wandbox/permlink/XRyIBwjIveJGTOri

**Comment by yumetodo** [comment]
そういえばポインタの先までconstは伝播しないんだった。修正します

**Comment by yumetodo** [comment]
修正しました、closeします。
@bolero-MURAKAMI ありがとうございました。
