### ISSUE TITLE
CMakeに対応させるべきかもしれない

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#65]
(文字コードの問題もあるので)正常に動くことはひとまず置いておいて、複数のコンパイラでコンパイルが通ることは重要だと考える。
現状
- VC
- Clang

が使えるが、gccもやはり確認するべきだろう。

Makefileを書くだけでいいかCMakeにするか考える
# 参考サイト

http://mhr380.hatenablog.com/entry/2015/02/11/223805

**Comment by sayurin** [comment]
正式な動作環境とするかしないかだと思います。単にコンパイルテストするだけなのであれば

```
g++ -O2 -o KCS_CUI *.cpp
```

で済みますから、Makefileどころかシェルスクリプトを用意しておくだけで十分ではないでしょうか？

**Comment by yumetodo** [comment]
うーん。個人的にはLinuxでも動いて欲しいのでとりあえずmsys2 mingwgccでコンパイルするだけのmakefile書きますかね・・・。

**Comment by yumetodo** [comment]
VSの設定を完全にCMakeから作るのは無理そうなので、makrfileを書く方向で

**Comment by yumetodo** [comment]
いや、VSのプロジェクトはのこしてそれ以外のためにcmake書くのは無意味ではないな。

**Comment by sayurin** [comment]
そういえばVS2015の次バージョン、VS15ではCMake対応が進められているそうで。

**Comment by yumetodo** [comment]
ほう。vcpkgに引き続きVSもですか
今cmake書いてます。conflict不可避なのでpull requestしませんが。

**Comment by yumetodo** [comment]
![image](https://cloud.githubusercontent.com/assets/10869046/19415145/0569954c-93a2-11e6-99c9-a8091dec29db.png)

ぎゃああああ、コンパイルエラーががが

**Comment by yumetodo** [comment]
ぜってービルドだけでもCIにかけておくべきだったな。これは。

**Comment by yumetodo** [comment]
#149

**Comment by yumetodo** [comment]
対応した
