### ISSUE TITLE
配布用バイナリにはdllを梱包する

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#67]
MSVCP140.dllがないため(ryを避けるために

**Comment by YSRKEN** [comment]
MSVCP140.dllだけで大丈夫でしたかしら？

**Comment by yumetodo** [comment]
```
VCOMP140.DLL
VCRUNTIME140.DLL
```

の2つですかね・・・。

**Comment by yumetodo** [comment]
![default](https://cloud.githubusercontent.com/assets/10869046/13898860/cfcf5c3e-ee22-11e5-884e-df4dbc2d6631.png)

**Comment by sayurin** [comment]
`api-ms-win-crt-*.dll`もWindows非搭載ですので再頒布の必要があります。
…といいつつ実はWindows 10からVC++2015 Runtimeを搭載するようになったので、

> Win10未満の方は[Visual Studio 2015 Update 1のVisual C++再頒布可能パッケージ](https://www.microsoft.com/ja-jp/download/details.aspx?id=49984)を導入してください

で済むかなと。
で、Visual Studio 2015 Update 2 RCではないところが厄介。

**Comment by yumetodo** [comment]
Visual Studio 2015 Update 2 RCのVisual C++再頒布可能パッケージはないのか

**Comment by sayurin** [comment]
存在していてインストールもされていて再頒布も可能ですが、Web公開されてないだけですね。

**Comment by yumetodo** [comment]
じゃあ当初提案通りzipで一緒に固めましょう。

**Comment by sayurin** [comment]
そういえばzipにdllを含めるくらいならstatic linkしてしまえばいいんでした。

**Comment by yumetodo** [comment]
え、それはそれでどうなんだろう・・・メモリー消費的に

**Comment by sayurin** [comment]
dllだとファイルに含まれる全関数をロードすることになりますが、static linkの場合は参照された関数のみをピックアップしてexeに埋め込むので、ファイルサイズ、メモリ消費の両方とも改善されますよ？ 加えて関数呼び出しもdll境界をまたぐ間接callから直接callに改善されます。

**Comment by yumetodo** [comment]
確かにdllを梱包する時点でdllによるメモリー節約は無意味どころか逆に増えるか。

**Comment by YSRKEN** [comment]
DLL同梱についてですが、どういった風にしましょうか？
再頒布可能パッケージを～だけにして、同梱せずで問題なく動作しますかね？

**Comment by sayurin** [comment]
#74 にて静的リンクすることでdllは不要に。

**Comment by yumetodo** [comment]
fixed
