### ISSUE TITLE
CSVの正規化

### ISSUE THREAD

**Issue by sayurin** [YSRKEN/KanColleSimulator_KAI#70]
#62 を取り込んでいただけたので、リポジトリルートにある `ships.csv` と `slotitems.csv` は不要になりました。

その上で特に `KCS_CUI/source/ships.csv` ですが、データを正規化しませんか？ ピリオド区切りはまだいいのですが、数値のところに`null`が出現するのはツライです。従来コードでもさらっとスキップしていて私もはまりました。
https://github.com/YSRKEN/KanColleSimulator_KAI/blob/aa52fa28779e12ef814d87dc7780d27aef6bec54/KCS_CUI/source/other.cpp#L138

CSV兼C++ソースコード化されているので`null`と記述するよりは行頭を

```
// SHIP(,～
```

としてくれると助かります。

**Comment by yumetodo** [comment]
https://github.com/YSRKEN/KanColleSimulator_KAI/blob/8c49fe13d24763935ef58e32891f81c90a221477/KCS_CUI/source/ships.csv

これか。そのほうが確かにいいですね

**Comment by YSRKEN** [comment]
そうですね。分からないデータが多いのでそういった仕様にしていましたが、組み込む場合には確かに不便ですわ……(なおGUI側ではCSVを読み込んでいるのでおちおち廃棄できない模様)

**Comment by yumetodo** [comment]
> GUI側ではCSVを読み込んでいるのでおちおち廃棄できない

なんやて！？
そっちもコンパイル時・・・ってC#だとできたっけ

**Comment by YSRKEN** [comment]
一通り処理が終わったと判断し、Closeします。
