### ISSUE TITLE
SaveSFileMenuItem_Clickメソッドの書き出し文字エンコード

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#79]
``` cs
var sw = new StreamWriter(FleetFilePath, false, Encoding.GetEncoding("shift-jis"));
```

現状Shift-JISになっている。ASCII文字しかないからどうでもいいのかもしれないが、UTF-8withBOMにしておくべきではないか？

``` cs
var sw = new StreamWriter(FleetFilePath, false, Encoding.GetEncoding(65001));
```

**Comment by YSRKEN** [comment]
BOM付きにすると今度は開けなかったおもひで

**Comment by yumetodo** [comment]
手元で実験した感じ動いているようですが・・・
![default](https://cloud.githubusercontent.com/assets/10869046/14057601/1dea4d32-f348-11e5-9d8e-f33dd6644fc0.png)

**Comment by YSRKEN** [comment]
BOM付きでも動くのでしたらUTF-8withBOMでも良いかと。あれ、もちろんCUIでもUTF-8withBOMのJSON食わせてよかったはずですわよね？

**Comment by YSRKEN** [comment]
あ、試したら動きましたｗ

**Comment by sayurin** [comment]
JSON読み書きまわりはばっさり書き換えてます。
https://github.com/sayurin/KanColleSimulator_KAI/tree/try-json
https://github.com/sayurin/KanColleSimulator_KAI/blob/try-json/KCS_GUI/Form1.cs#L1386
