### ISSUE TITLE
Weapon::Weapon()をnoexceptに

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#8]
# 提案内容

現在

``` cpp
Weapon::Weapon() : Weapon(-1, L"なし", kWeaponClassOther, 0, 0, 0, 0, 0, 0, 0, 0, 0, kRangeNone, 0, 0){}
```

のようになっているがこれはnoexceptにできない。なぜならば

``` cpp
basic_string(const charT* s, const Allocator& a = Allocator());
```

N4296によればこれは内部でalocateしcopyするからである。

そこで

``` cpp
Weapon::Weapon() noexcept : Weapon(-1, {}, kWeaponClassOther, 0, 0, 0, 0, 0, 0, 0, 0, 0, kRangeNone, 0, 0){}
```

のようにすることを提案する。(ただし、C++11の範囲ではnoexceptになっていないのでコンパイル時に`-std=c++14`は必要である。Visual Studio 2015の実装はnoexceptである)

N4296によれば

``` cpp
basic_string() noexcept : basic_string(Allocator()) { }
```

これはnoexceptである
# 影響

``` cpp
const std::wstring& Name() const noexcept;
std::ostream & operator<<(std::ostream & os, const Weapon & conf);
std::wostream & operator<<(std::wostream & os, const Weapon & conf);
```

のみでクラスメンバー`name_`は使用されている

**Comment by YSRKEN** [comment]
@yumetodo ところでコンストラクタにnoexcept指定をする意味って何かあるのでしょうか？
いや、「メモリが確保できないとシミュレートしようがないから落とす」といった意味があるのかもしれませんが……

**Comment by yumetodo** [comment]
@YSRKEN 
コンパイラが最適化しやすくなります
また、今回はあまり関係ないですが、そのクラスを利用したクラス・関数が実装しやすくなることもあります

**Comment by yumetodo** [comment]
@YSRKEN 
というかなし、と書く位なら空にしよう、という話です。むだな動的確保を減らせます

**Comment by YSRKEN** [comment]
存在しない値について艦名を「なし」にするのは元データ(ゲームから解析したデータ)の仕様なのですが、まあこだわる意味は無いので「L"なし"」を「{}」にして良いと思います。

**Comment by yumetodo** [comment]
わかりました、作業します

**Comment by yumetodo** [comment]
完了しました。確認してcloseお願いします
