### ISSUE TITLE
ファイル名表示欄を作る

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#84]
現状だとファイルを開けているのかどうかわかりにくい。
そこで、
![default](https://cloud.githubusercontent.com/assets/10869046/14052182/93c22620-f30b-11e5-86f4-2ca1ecce4d48.png)
のようにファイル名を表示する。
背景色は「新規」もしくは「開く」で開く前は`System.Drawing.SystemColors.Menu`、
その後は`System.Drawing.Color.FromArgb(235, 246, 247)`、
何らかの変更があったら`System.Drawing.Color.FromArgb(253, 239, 242)`
に変更する
# 課題

「何らかの変更があったら」の実現にはtextboxほぼすべての変更操作を行うevent handlerに処理を追加しなければならないが、面倒そう

**Comment by yumetodo** [comment]
つまりどっかに

``` cs
enum FileStatus {
    invide,
    modified,
    saved
};
```

とかして、フラグを作らないといけないのか。

**Comment by yumetodo** [comment]
NextAnyEventとかあればいいんだけどなぁ、ないし。

**Comment by YSRKEN** [comment]
開いているファイル名はステータスバーかタイトルバーに出した方がスマートっぽい？

**Comment by yumetodo** [comment]
ではステータスバーにします・・・？
