### ISSUE TITLE
対応コンパイラについて

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#89]
#74 より。

とりあえず
- Visual Studio 2015 Update1
- Visual Studio 2015 Update2 RC
- Visual Studio 2015 Clang with Microsoft CodeGen (January 2016)

で、将来的に
- msys2 mingw32/64 gcc 5.2.0
- msys2 mingw32/64 clang 3.8.0
- linux x86/64 gcc 6.0.0
- linux x86/64 clang 3.9.0

あたりも考えればいいと思うが、少なくともReadmeに書くべきだし、何か異議があれば

**Comment by sayurin** [comment]
Visual Studio 2015 Update2がリリースされました。
併せてVisual Studio 2015 Clang with Microsoft CodeGen (March 2016)に更新されています。

**Comment by yumetodo** [comment]
おお

**Comment by yumetodo** [comment]
それとは別に次期バージョンであるVisual Studio “15” Previewも出てるな。

ところで

> https://www.visualstudio.com/news/vs15-preview-vs#Cdoubleplus
> We’ve implemented every C++ Standard Library feature that's been voted into C++11, C++14, and the C++17-so-far Working Paper N4567 (pre-Jacksonville).

・・・え！？N4567 の実装全部終わったの？ライブラリ部分

**Comment by sayurin** [comment]
実装されたのかよくわかりませんが、VS2015リリース前後でC++17最速実装をめざすと宣言してましたよ。

**Comment by yumetodo** [comment]
そういえばそんなこと言ってたけど、結構頑張ってるな・・・。
早いところ`__cplusplus`の値を更新してもらいたいものだ。
