### ISSUE TITLE
Tupleでboost::optionalもどきのことをするのをやめる

### ISSUE THREAD

**Issue by yumetodo** [YSRKEN/KanColleSimulator_KAI#94]
C#には`Nullable<T>`と`Option<T>`が存在します。
http://bleis-tift.hatenablog.com/entry/cmp_Option_Nullable

なので

``` cs
Tuple<MapData, bool> setMapData = ReadMapFile(MapFilePath);
if(!setMapData.Item2)
    return;
```

こういう時は`Option<T>`を使用するべきではないでしょうか？

@YSRKEN

**Comment by yumetodo** [comment]
いや、待てよ。`ReadMapFile`の定義覗いたけど、これ`setMapData.Item2`はfalseにならないのでは？

**Comment by sayurin** [comment]
`Option`は存在しません。ぐるぐるさんの自作ライブラリ`LangExt`の話です。
まぁこの辺りはいろいろ書き換えるので、お待ちください。

**Comment by yumetodo** [comment]
了解です
